name: Mirror To Codeberg
on: [push]
jobs:
  Miror-To-Codeberg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: yesolutions/mirror-action@master
      with:
        REMOTE: 'ssh://git@codeberg.org/alxd/storyseedlibrary.git'
        GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
        GIT_SSH_NO_VERIFY_HOST: "true"